### ISSUE TITLE
Feature Request: Add ability to customize the amount of movies/tv shows

### ISSUE THREAD

**Issue by gbdavidx** [JurajNyiri/PlexMeetsHomeAssistant#1]
FR: Add ability to customize the amount of movies/tv shows, also add the option to last 10 / 20 / 30 ect last movies added in plex, last tv shows updated in plex

**Comment by gbdavidx** [comment]
also, customize the amount of rows/tv shows so your not scrolling forever

**Comment by JurajNyiri** [comment]
Done. Sorting has been added, maxCount has been there and search now works globally.
