### ISSUE TITLE
Failed to call service rest_command/pmha_playmedia. Service not found

### ISSUE THREAD

**Issue by image969** [JurajNyiri/PlexMeetsHomeAssistant#102]
When trying play a movie it instantly gived me this message

https://github.com/JurajNyiri/PlexMeetsHomeAssistant/issues/82

I put a script in to wait 10 seconds, this produces the same error after 10 seconds passes. 

Happening on all of my roku devices. I cannot find a fix to this anhywhere. Just several people having the same trouble. 

Is there a solution yet?

**Comment by JurajNyiri** [comment]
https://github.com/JurajNyiri/PlexMeetsHomeAssistant/issues/32#issuecomment-908614426

**Comment by JurajNyiri** [comment]
Continue in https://github.com/JurajNyiri/PlexMeetsHomeAssistant/issues/82
