### ISSUE TITLE
Script Execution After Starting Media

### ISSUE THREAD

**Issue by johnoldiges** [JurajNyiri/PlexMeetsHomeAssistant#103]
This is probably not a bug but if not then I think this need to have a 3rd option. When executing a script after media start it executes within seconds. If this is how it is supposed to behave then I would like to request a 3rd option for Execute Script on Media End. Say as to have some lights ramp up to a dim level after a media item ends.

**Comment by image969** [comment]
You should be able to run a script that when you leave this page in HA, upon pressing the back button(or whatever button you create), to also change the lights to your liking when movie time is over

On that note, can you please confirm for me that this Plex app is still working. i can't get an answer from anyone including the developer. I'm one of many getting the error "Failed to call service rest_comman/pmha_playmedia. Service not found".....When trying to press play

Would love for someone to tell me why this is happening.

**Comment by JurajNyiri** [comment]
This can be handled by automation in HA. Closing.
