### ISSUE TITLE
Play button grayed out

### ISSUE THREAD

**Issue by FSFirenze** [JurajNyiri/PlexMeetsHomeAssistant#105]
Dear all,
apologize if this is not the right place to post, as mine could be just a config issue rather than a bug, or maybe a request for new functionalities.

I run both Plex and Homeassistant in Docker containers on a Raspberry PI. I can reach both homeassistant and Plex from a machine on the same network with the addresses http://192.168.1.100:8123 and http://192.168.1.100:32400 respectively.
I can also reach Homeassistant from the outside world on https, thanks to a combination of duckDNS and Ngnix reverse proxy (that handles the SSL certificates).
I configured this Card to communicate to Plex via http, as follows:

          type: custom:plex-meets-homeassistant
          ip: 192.168.1.100
          port: 32400
          token: H6ukgJ4ow2sQbUhku821
          libraryName: Music
          entity: media_player.living_room
          protocol: http
          sort: titleSort:asc
          displayType: ''
          playTrailer: true
          showExtras: true
          showSearch: true

...and i can successfully see my playlists and surf them.... **however I can't play anything, because the Play button is not Yellow, but Grayed out!**

I am specifying the above because I think I should be able to use the http protocol, as I am trying to do everything from inside my network, but also I saw the "If you are using Home Assistant via HTTPS, you need to specify port https for Plex and have Plex available on https connection with a valid and working certificate." disclaimer on the readme.

I am trying to use this Card to control Plex and redirect the audio output to a Bose Home Speaker 450 which also runs Alexa and is visible on the same network, address 192.168.1.110.
I also saw in the readme that this card may only work with Android TV, Kodi, Google Cast, so this could be my problem.

Home Assistant seems to be able to send audio files to The Bose Speaker via **DLNA**, but maybe the issue is that DLNA is not supported by this card?

I can also successfully ask Alexa on my Bose Home Speaker 450 to play a Plex playlist and she would.
This Bose Speaker has also an option to enable **Chromecast**, if this could be helpful.

My ask to you is .... where do you think the issue is? and ... is there any alternative connections you may recommend I try, before giving up?

Thank you for your time!

**Comment by JurajNyiri** [comment]
You can try Chromecast. See supported methods in readme.

Button is grayed out if the target device is available and it is expected and correct. See detailed readme for more details.

**Comment by FSFirenze** [comment]
Thank you JurajNyiri, appreciate your patience thru this. My play button is now yellow(yay!), using ChromeCast as recommended.
However by clicking on the Play button, almost nothing happens. The speaker does receive some commands, namely it turnes on and gives a beep as a feedback, however no music streaming is initiated.
Any suggestions on what I should be looking next?
