### ISSUE TITLE
General question

### ISSUE THREAD

**Issue by sahara101** [JurajNyiri/PlexMeetsHomeAssistant#109]
Hi! 

Sorry for posting here. I am trying to integrate plex with node-red for random unwatched movie playback.
I cannot for the life of me understand how I need to define the API call in order to start a playback....can you help me?

Thanks!

**Comment by JurajNyiri** [comment]
You can investigate this code or https://plexapi.dev/docs/plex. There are many different ways how to launch playback depending on what you use on your client device.
