### ISSUE TITLE
HASS Iphone App -- Plex Server Did not respond

### ISSUE THREAD

**Issue by mew0717** [JurajNyiri/PlexMeetsHomeAssistant#11]
Have this rendering in a browser just fine, but I get this error on the Home Assistant iPhone app:

Error: Plex server did not respond
Details of the error:  Network Error while requesting url:  "http://192.17.x.x:32400/clients?X-Plex-Token=TOKEN".

**Comment by JurajNyiri** [comment]
https://github.com/JurajNyiri/PlexMeetsHomeAssistant/issues/5
https://github.com/JurajNyiri/PlexMeetsHomeAssistant/issues/3

**Comment by mew0717** [comment]
The iphone results in a blank screen, where as the desktop browser provides:
```
<MediaContainer size="1">
<Server name="Roku 4 - YY0001438323" host="192.168.7.31" address="192.168.7.31" port="8324" machineIdentifier="f617628bdc042bc82a1764ac8b730b9c" version="6.7.24.7009-0d0d064dd-Plex" protocol="plex" product="Plex for Roku" deviceClass="stb" protocolVersion="1" protocolCapabilities="timeline,playback,navigation,playqueues"/>
</MediaContainer>
```

**Comment by JurajNyiri** [comment]
The url also needs to work on your iPhone. If it doesn't it will not work..
