### ISSUE TITLE
Feature Request: Shared Libraries

### ISSUE THREAD

**Issue by vsilvar** [JurajNyiri/PlexMeetsHomeAssistant#14]
Currently shared plex libraries are not supported.
They are displayed correctly, but can't be played as the player won't be found in that server.

It would be nice if an extra option could be added to allow to specify both the library server IP and the player server IP.
I think it would then be possible to adjust the code to allow playing shared libraries.

**Comment by JurajNyiri** [comment]
Just to clarify, this is only a concern for plexPlayer type of player right?

**Comment by vsilvar** [comment]
Ah yes, it is indeed regarding the plexPlayer type

**Comment by JurajNyiri** [comment]
This took **a lot** more effort then I originally anticipated but is now supported in 1.3! See [detailed instructions](https://github.com/JurajNyiri/PlexMeetsHomeAssistant#all-other-plex-clients).

**Comment by vsilvar** [comment]
Just tried it and it works great!
Thanks!
