### ISSUE TITLE
Network Error

### ISSUE THREAD

**Issue by Mermyx** [JurajNyiri/PlexMeetsHomeAssistant#24]
I keep getting this error

![image](https://user-images.githubusercontent.com/62225333/127004290-28eb2325-c7f7-4ec9-91b0-ae2f90b9f5fa.png)

**Heres my code:**

```
type: custom:plex-meets-homeassistant
protocol: http
playTrailer: true
showExtras: true
showSearch: true
ip: 192.168.70.74
token: ****************************
libraryName: Films
port: '32400'
entity:
  - media_player.apple_tv
  - media_player.plex_plex_for_windows_desktop_400armt

```

does this have something to do with my plex install or is there something wrong with the code.

**Comment by JurajNyiri** [comment]
Are you accessing Home Assistant through HTTPS? If yes, you cannot use http, thats why also in the newest version with UI, UI doesn't offer the option.

**Comment by Mermyx** [comment]
that did the trick


thank you
