### ISSUE TITLE
[Feature Request] Plex Smart Collections

### ISSUE THREAD

**Issue by Tommatheussen** [JurajNyiri/PlexMeetsHomeAssistant#28]
It would be really nice if instead of a library, you could specify 1 of your Smart Collections (https://support.plex.tv/articles/201273953-collections/)
Not 100% sure if you can easily get that info from the API, but it's possible to show these collections on the Home Page (similar to On Deck), so maybe they could be implemented as a special library.

I'm open for testing if you need anybody!

**Comment by JurajNyiri** [comment]
Implemented in [2.1](https://github.com/JurajNyiri/PlexMeetsHomeAssistant/releases/tag/2.1) along with playlists!

**Comment by Tommatheussen** [comment]
Awesome! Thanks for the quick addition, now I'm off to create my complete media center dashboard :D
