### ISSUE TITLE
Unable to connect to HA (Android Companion app)

### ISSUE THREAD

**Issue by r0667002** [JurajNyiri/PlexMeetsHomeAssistant#3]
HA-version: core-2021.4.3
Media server: Plex add-on for HA

I used the token provided by app.plex.tv (get info->XML->URL) and the card works great on my laptop, but the moment I try it in another browser I get a network error.

Trying it in the companion app for android makes things worse: I get a popup saying "unable to connect to HA". This is definitely due to the card, since it only happens when I go to the view where the card is in. Pressing 'wait' eventually gives the same network error as in another browser.

Any ideas what might be causing this?

(I absolutely love the look and feel of this card btw, great job!!)

My card config:
```type: 'custom:plex-meets-homeassistant'
token: xxxxxx
ip: 192.168.0.193
port: 32400
libraryName: Series
protocol: https
maxCount: 100
entity:
  plexPlayer: media_player.plex_plex_cast_chromecast
```

**Comment by r0667002** [comment]
HA-version: core-2021.4.3
Media server: Plex add-on for HA

I used the token provided by app.plex.tv (get info->XML->URL) and the card works great on my laptop, but the moment I try it in another browser I get a network error.

Trying it in the companion app for android makes things worse: I get a popup saying "unable to connect to HA". This is definitely due to the card, since it only happens when I go to the view where the card is in. Pressing 'wait' eventually gives the same network error as in another browser.

Any ideas what might be causing this?

(I absolutely love the look and feel of this card btw, great job!!)

My card config:
```type: 'custom:plex-meets-homeassistant'
token: xxxxxx
ip: 192.168.0.193
port: 32400
libraryName: Series
protocol: https
maxCount: 100
entity:
  plexPlayer: media_player.plex_plex_cast_chromecast
```

**Comment by JurajNyiri** [comment]
Thank you! 

You are using https on ip which by definition cannot have valid certificate. Either use HTTP with http home assistant or use https with a domain with valid certificate for plex.

It might be working in your browser because you accepted invalid certificate and added exception which you have not done on your app(might not be possible).

**Comment by r0667002** [comment]
Ah, makes sense! Thanks for the quick reply!

**Comment by r0667002** [comment]
Can I ask how you are implementing this? Because you obviously want to use home assistant with https if remote access is enabled. Might be handy to link some sort of tutorial in the readme so the card becomes more usable to the general public :)

**Comment by JurajNyiri** [comment]
You mean how to use https with plex? There's a lot of ways and great number of easy to follow tutorials and I consider it out of scope of this card. 
I for example am using nginx reverse proxy with let's encrypt and my domain (but you could easily use duckdns for example).

**Comment by siaox** [comment]
@JurajNyiri  thanks for the great work on this - I too am using a traefik reverse proxy - HA on https. Unable to access the addon via the companion app. All i could find was this:

https://support.plex.tv/articles/206225077-how-to-use-secure-server-connections/

Would you have any other documentation I could take a look at?

Again Great Work!

**Comment by JurajNyiri** [comment]
Hey, I do not know traefik reverse proxy.

I assume you would set up your local plex ip similarly to how you did hass.

You can google for nginx reverse proxy there are tons of articles.
