### ISSUE TITLE
Add HTTP Option or ignore Certificate on HTTPS

### ISSUE THREAD

**Issue by bluenazgul** [JurajNyiri/PlexMeetsHomeAssistant#31]
Running latest HACS Version and being unable to Connect via https (local Certificate issue) sadly there is no way to ignore this or run in http mode

**Comment by bluenazgul** [comment]
![Screenshot_20210825_135327](https://user-images.githubusercontent.com/171537/130786175-5b27a742-c246-437b-a615-19f277d2a432.jpg)
It changes nothing if I use 443 or 32400 or none

I cant select http, my HA is running https the plex Server is running on another Maschine. 
http is working via Browser, https results in Certificate issue.

That's why this "Integration" should also need an Option to access plex via http even if HA is running on https

**Comment by JurajNyiri** [comment]
HTTP is available when accessing Home Assistant via HTTP.
HTTPS would not work when accessing Home Assistant through HTTP as [per this big notification right at the start of readme.](https://github.com/JurajNyiri/PlexMeetsHomeAssistant#important-notice).

Works as expected, closing.
