### ISSUE TITLE
Can't view when not on the same network

### ISSUE THREAD

**Issue by sjikkervisje** [JurajNyiri/PlexMeetsHomeAssistant#33]
It works only when I'm at home connected to the same network. As soon as I want to view my plex database outside the house, like via my mobile phone then it no longer works.

**Comment by JurajNyiri** [comment]
https://github.com/JurajNyiri/PlexMeetsHomeAssistant#important-notice

Also duplicate of https://github.com/JurajNyiri/PlexMeetsHomeAssistant/issues/31, https://github.com/JurajNyiri/PlexMeetsHomeAssistant/issues/24, https://github.com/JurajNyiri/PlexMeetsHomeAssistant/issues/11, https://github.com/JurajNyiri/PlexMeetsHomeAssistant/issues/6 and https://github.com/JurajNyiri/PlexMeetsHomeAssistant/issues/5 .

It is right at the start of readme, I do not know how to make it larger and more visible.
