### ISSUE TITLE
Bug: Name not showing properly in new Sidebar View

### ISSUE THREAD

**Issue by sjikkervisje** [JurajNyiri/PlexMeetsHomeAssistant#35]
I'm using the new Sidebar View in Home Assistant as it works better to show the various plex libraries however the name is not showing properly here.
![image](https://user-images.githubusercontent.com/1422692/131337936-f69dcb8f-0cc9-4d69-93cb-46d167ec0258.png)

**Comment by JurajNyiri** [comment]
Fixed in 2.1.1.
