### ISSUE TITLE
Bug: card does not wait for script to finish before attempting to play media so player is not available yet

### ISSUE THREAD

**Issue by ned786** [JurajNyiri/PlexMeetsHomeAssistant#36]
card does not wait for script to finish before attempting to play media so player is not available yet. even though i have set the wait time in my script to run before play to wait 40 seconds at the end to allow the plex player to become available (and this is confirmed by also getting the script to turn on a lamp). however it attempts to play after approx 10 seconds of pressing play and a error message is displayed.

1. make a script to turn on tv, wait for trigger for it to change state, change source to plex, wait 40 seconds,
2. add this script to plex card in section run script before play media
3. make sure tv is off, select media press play, wait 10 seconds homeassistant says Failed to call service rest_command/pmha_playmedia. Service not found

**Expected behavior**
i would expect the card to only attempt to play media after the 40 second wait so when the lamp turns on the media should start.

**Comment by JurajNyiri** [comment]
So I did some investigation.

Card does wait for home assistant to return data in both cases - script with 1 sec delay and script with 30 sec delay.

In the case of one with 30 sec, Home Assistant chooses to return a response after just 10 seconds.

I reached out to devs on Home Assistant discord channel as this doesn't seem to be documented anywhere.

**Comment by JurajNyiri** [comment]
Fixed in 2.2.1.

**Comment by ned786** [comment]
> Fixed in 2.2.1.

hi, thank you for fixing in 2.2.1 it worked perfect. however i have now updated the plex integration and the same problem has come back. can you please fix the bug?

**Comment by JurajNyiri** [comment]
Hmmmm, that code wasn't touched. Are you sure its still behaving like before? 10 sec max?
