### ISSUE TITLE
Search function is limited to maxCount of items

### ISSUE THREAD

**Issue by Garulf** [JurajNyiri/PlexMeetsHomeAssistant#4]
listing 1,000's of movies puts lovelace into a never ending loading cycle. And using the maxCount option limits your choices to a very small amount of items and limits the search to those items.

**Comment by JurajNyiri** [comment]
This is one of the planned features along with others listed in first post in HASS community. I will get to it eventually in a few weeks or months, currently I am busy with work.

PRs are welcomed!

**Comment by Garulf** [comment]
I apologize I came straight from HACs to GitHub and didn't see that was a planned this was already discussed. 

This card has awesome potential.

**Comment by JurajNyiri** [comment]
Done. Sorting has been added too: https://github.com/JurajNyiri/PlexMeetsHomeAssistant#sorting
