### ISSUE TITLE
[Bug] Default libraries won't display

### ISSUE THREAD

**Issue by paco3346** [JurajNyiri/PlexMeetsHomeAssistant#41]
**Describe the bug**
Cannot get any libraries whose name is prepended with a space to load. Since HASS auto formats the yaml and removes the extra space when I try to prepend I cannot manually work around this. (Libraries & Collections not prepended with a space work as expected.)

**To Reproduce**
1. Set up with Plex server that prepends library name with a space
2. Try to create card using said library

**Expected behavior**
What happens makes sense (not an exact string match). Would be nice if it was possible to prepend spaces in the library name in the yaml or if the code would `trim()`

**Screenshots**
See value of library name bottom right:
![image](https://user-images.githubusercontent.com/3145247/133729998-e6582e8c-ddb2-45d2-8e35-af90066756b8.png)

Value in JSON payload directly from Plex server:
![image](https://user-images.githubusercontent.com/3145247/133730563-13c01c67-cadd-4880-9f58-25a54a40f9eb.png)

**Checks**
Please check below if true:

[X] I am running Home Assistant on HTTP protocol
[ ] I am running BOTH Home Assistant AND Plex on HTTPS protocol
[X] My Plex server is accessible through protocol, port and ip/hostname I have specified for the card.
[X] My Plex server is running on HTTPS and has a valid certificate.

**Card Version**
2.4.2

**Plex Version**
1.24.3.5033-757abe6b4

**Additional context**

**Comment by JurajNyiri** [comment]
What is the use case to have space in a library in Plex?
It is technically a bug and I will fix it, just wondering...

**Comment by JurajNyiri** [comment]
Could you do Code editor and then 
```
libraryName: ' Movies'
```

Does the selection of library with prefixed space not work in UI configurator?

**Comment by paco3346** [comment]
I don't necessarily think there is a use-case for having a prepended space. The Plex server is run by a friend of mine who shared his content with me so I don't have access to it to debug why it's prepended.

I tried manually adding the space via the code editor but as soon as the YAML validation runs it automatically trims it.

I was able to get it working locally by adding 3 `trim()`s but arguably what I did was a workaround as I'm no longer truly matching strings. I'd put in a PR with the changes but I'm pretty new to HASS and don't know enough about the ecosystem to know if the YAML validation is handled by HASS itself or custom components.

**Comment by JurajNyiri** [comment]
I just started looking into this, it

**Comment by paco3346** [comment]
Cool, that feels 'more correct' to me to truly match the library name coming from Plex. I'll give these changes a try when I get home tonight.

**Comment by JurajNyiri** [comment]
Just a heads up, I have to leave soon so fix will not be available today, maybe during the weekend I will be able to get to it.

**Comment by paco3346** [comment]
No rush, my local changes mean it's technically working at the moment. I'll follow up early next week.

**Comment by JurajNyiri** [comment]
@paco3346 should be working now in the latest main branch - not released yet. I need to clean it up and will release it during the weekend. Please let me know if you get the chance to test. I tested through UI config.
