### ISSUE TITLE
Feature Request: Add Music to the Plex integration

### ISSUE THREAD

**Issue by jorgemonteiro** [JurajNyiri/PlexMeetsHomeAssistant#43]
Currently the integration already supports getting all artists, here is a screenshot of it:

[image](https://www.icloud.com/iclouddrive/0xVKwlww5SG4T8pdAFgQmgP0w#Screen_Shot_2021-09-27_at_12.08.25_PM)

Clicking on a single artist, opens the page correctly - with a few exceptions (what needs to be done)
[image](https://www.icloud.com/iclouddrive/0IDnc21mS_A2DaFoS5txewE0Q#Screen_Shot_2021-09-27_at_12.14.58_PM)

What needs to be done:
1) Add the albums for each artists, just like it is done on the TV Episodes, in the artist page
2) When clicking on a albums go into the albums paga, show all songs for the album
3) At any level, artists, album, allow playing, so we can play songs for an artist, an album or just select a single song and play it

Awesome extras:
1) A shuffle on the play would be great, this should be both at the top level, artist level or album level
2) Add an extra filter: genres. If a genre is selected, only songs for that genre would be shown. Display should follow the same idea artists -> albums -> songs

**Comment by jorgemonteiro** [comment]
To grab the genres:

${this.getBasicURL()}/library/sections/${sectionID}/genre

**Comment by JurajNyiri** [comment]
This is now available in branch https://github.com/JurajNyiri/PlexMeetsHomeAssistant/tree/music .
You can test it out by manually downloading and replacing /dist/.js file. Make sure to also delete map and gz files created by HACS, clear cache etc.

Full support for music is available on cast, android TV and plexPlayer. 
I want to add 2 more things before release:
1.) Kodi support
2.) Different look for tracks once an album is opened.

**Comment by jorgemonteiro** [comment]
Thank you. Going to install it right now 😀

**Comment by jorgemonteiro** [comment]
It already looks amazing but yeah you are correct, the songs view needs to change, it should be just a simple table with

Track number | Track name | Track time

No need for image since the image is just for the album and it is already on the top. This is awesome, now I can play all my music using HA 😀

**Comment by JurajNyiri** [comment]
Implemented in 3.1 https://github.com/JurajNyiri/PlexMeetsHomeAssistant/releases/tag/3.1
