### ISSUE TITLE
Works on PC but on TV: "An error occurred loading items into the play queue"

### ISSUE THREAD

**Issue by blaktro** [JurajNyiri/PlexMeetsHomeAssistant#45]
Plex viewers are PC (with plex server on it) and TV LG, both in the same local network.
Card nicely discoveers both of them. Content from plex chosen using your card is runnig on PC viewer instantly.
But when I set the device in card as TV and play a movie it starts loading for several seconds and then i got info on tv screen  "An error occurred loading items into the play queue".
My config is straightforward, I use http.

**Comment by JurajNyiri** [comment]
Create issue using bug template. Fill it out properly.

**Comment by blaktro** [comment]
Reason behind problem wasn't  PlexMeetsHomeAssistant.
I installed another Plex server this time on HA and somehow after switchng between servers it started working properly.
.
