### ISSUE TITLE
Error: Plex Server did not respond

### ISSUE THREAD

**Issue by override80** [JurajNyiri/PlexMeetsHomeAssistant#5]
Hi, I get an error when trying to connect with my Plex Server.

![Screen Shot 2021-05-18 at 13 42 13](https://user-images.githubusercontent.com/43748388/118645425-3afa3c00-b7df-11eb-9d0d-7baea4962f00.png)

After adding the integration via HACS, I am trying to add it to lovelace using the following configuration in the card:

![Screen Shot 2021-05-18 at 13 43 05](https://user-images.githubusercontent.com/43748388/118645547-5b29fb00-b7df-11eb-81f1-db4ae43ddd4d.png)

I fetched the Token following the instructions, manally running a curl from inside hassio homeassistant container returna valid (?) XML response:

![Screen Shot 2021-05-18 at 13 46 22](https://user-images.githubusercontent.com/43748388/118645724-9298a780-b7df-11eb-8edc-bb7679d30205.png)

I am wondering if this might be related to Plex Server version, mine is pretty outdated (Version 1.9.6.4429) but I cannot find any more recent version that works on my QNAP TS-650.

**Comment by JurajNyiri** [comment]
Do you have HASS on https?

**Comment by JurajNyiri** [comment]
As per readme, you need to use HTTP HASS with HTTP or HTTPS and if you are running HTTPS hass you can only use plex on HTTPS.

**Comment by override80** [comment]
Right, makes sense, I missed that in the readme!

Thankyou!
