### ISSUE TITLE
Feature Request: Play Audio Tracks in Track Sequence

### ISSUE THREAD

**Issue by MidnightRacer99** [JurajNyiri/PlexMeetsHomeAssistant#55]
Currently audio tracks appear to play in a random order.

It would be great to have them play in track order like they do within plex.

Many Thanks.

**Comment by danpowpow** [comment]
+1 on this feature request.
I love listening to albums through plex to chromecasts, and finding this custom card felt like an absolute gamechanger! Was surprised to see that 'shuffle' play as default is by design.

**Comment by JurajNyiri** [comment]
Implemented in [3.3.2](https://github.com/JurajNyiri/PlexMeetsHomeAssistant/releases/tag/3.3.2).

![image](https://user-images.githubusercontent.com/5785999/143091770-59d2a175-db2d-437d-9a65-cd6b63aee1eb.png)
