### ISSUE TITLE
Issue with playback on LG TV

### ISSUE THREAD

**Issue by sturgeo** [JurajNyiri/PlexMeetsHomeAssistant#56]
**Describe the bug**
Card retrieves movies and displays them OK. If I select a web player, it works, if I select my LG TV it fails. Both options are set as PlexPlayer from the device dropdown.

**Expected behavior**
Expect it to play the media on the TV

**Checks**
Please check below if true:

[ ] I am running Home Assistant on HTTP protocol
[X ] I am running BOTH Home Assistant AND Plex on HTTPS protocol
[X] My Plex server is accessible through protocol, port and ip/hostname I have specified for the card.
[X] My Plex server is running on HTTPS and has a valid certificate.

**Card Configuration**
type: custom:plex-meets-homeassistant
protocol: https
sort: titleSort:asc
displayType: ''
playTrailer: true
showExtras: true
showSearch: true
ip: plex.XXXXXXXXXXXXXXXX
token: XXXXXXXXXXXXXXX
port: ''
libraryName: Movies
maxCount: ''
maxRows: '10'
useHorizontalScroll: 'No'
displayTitleMain: 'Yes'
displaySubtitleMain: 'Yes'
minWidth: ''
minEpisodeWidth: ''
minExpandedWidth: ''
fontSize1: ''
fontSize2: ''
fontSize3: ''
fontSize4: ''
minExpandedHeight: ''
title: ''
entity:
  - plexPlayer | Chrome | 192.168.1.100 | XXXXXXXXXXXXXXXXXXX
  - plexPlayer | LG 43UK6400PLF | 192.168.1.100 | XXXXXXXXXXXXXXXXX

**Card Version**
3.3.1

**Plex Version**
1.24.5.5160

**Comment by blaktro** [comment]
I think it's related to this:
https://www.reddit.com/r/PleX/comments/pzgc1f/lg_webos_plex_issues_started_yesterday/
