### ISSUE TITLE
Oops something went wrong

### ISSUE THREAD

**Issue by Trigun** [JurajNyiri/PlexMeetsHomeAssistant#57]
Hi, thank you for this great app, I assume.
once using the this integration from home assisant and trying to cast it to my Chromecast.
I receive the following error: Oops, Someting went wrong.

perhaps any idea?

thanks in advance!

**Comment by JurajNyiri** [comment]
Does casting work through https://www.home-assistant.io/integrations/cast/#plex ? There have been users mentioning this and it seems to be Home Assistant issue.

**Comment by Trigun** [comment]
I'll check it out, thanks a lot for your reply!

**Comment by JurajNyiri** [comment]
https://github.com/home-assistant/core/issues/59493
