### ISSUE TITLE
Error: Plex Server did not respond (on https) On http working good.

### ISSUE THREAD

**Issue by spider7611** [JurajNyiri/PlexMeetsHomeAssistant#6]
I have problem on https.
On http it is working ok, but on https I have no port number for my plex server.
But in the configuration can't remove the port: 32400 definition because see the red error.
Can you solve this?

**Comment by JurajNyiri** [comment]
Put in 443 in https.

**Comment by adizag** [comment]
@JurajNyiri I got here to this issue by chance but your answer solved my problem after a few hours! Had a problem seeing the card on my android phone.

I advise you to explain that in the read.me.

TNX for your great work!

**Comment by JurajNyiri** [comment]
@adizag good point. Port is no longer mandatory in 1.0.2.
