### ISSUE TITLE
Feature Request: Next/Previous for music playback

### ISSUE THREAD

**Issue by pavolholes** [JurajNyiri/PlexMeetsHomeAssistant#62]
Can we get Next and Previous for the music playback?

**Comment by JurajNyiri** [comment]
This is not something I am planning to add, you can use sidebar panel with media playback control cards on the right.

**Comment by pavolholes** [comment]
Hi Juraj,
sure, I can add the media playback control to lovelace. But it's not available for the "media_player" device/entity. 

When I try to call service:
```
service: media_player.media_next_track
data: {}
target:
  entity_id: media_player.plex_plex_cast_chromecast
```
nothing is happening.

Also for this nothing is happening:
```
service: media_player.media_next_track
data: {}
target:
  entity_id: media_player.kuchyna_google_home_mini

```

Am I missing something? Or the official Plex integration is missing this media control?

Thank you.

**Comment by JurajNyiri** [comment]
I would have to research it as I do not use this functionality. I would assume there must be some kind of media control via some card or service in Home Assistant, but I don't have any experience with it.
