### ISSUE TITLE
Pre-roll video not playing

### ISSUE THREAD

**Issue by L1p0-M** [JurajNyiri/PlexMeetsHomeAssistant#64]
**Describe the bug**
Pre-roll video not playing with showExtras: true!

**To Reproduce**
1. Set a pre-roll (https://support.plex.tv/articles/202920803-extras/)
2. Set showExtras to true
3. Play movie
4. The movie starts without pre-roll

**Expected behavior**
I expected to see my pre-roll video before the movie.

**Checks**
Please check below if true:

[ ] I am running Home Assistant on HTTP protocol
[X] I am running BOTH Home Assistant AND Plex on HTTPS protocol
[X] My Plex server is accessible through protocol, port and ip/hostname I have specified for the card.
[X] My Plex server is running on HTTPS and has a valid certificate.

**Card Configuration**
```
type: custom:plex-meets-homeassistant
protocol: https
sort: titleSort:asc
displayType: ''
playTrailer: false
showExtras: true
showSearch: false
ip: myurl
token: mytoken
entity:
  - cast | media_player.chromecast_tv
libraryName: Filmek
useHorizontalScroll: 'No'
useShuffle: 'No'
displayTitleMain: 'Yes'
displaySubtitleMain: 'Yes'
style:
  .: |
    ha-card {
        background: rgba(28, 28, 28, 0.7) !important;
        box-shadow: none !important;
      }

```
**Card Version**
3.3.2

**Plex Version**
1.25.2.5319

**Comment by JurajNyiri** [comment]
`showExtras` are for showing extras in UI under the movie description when opened. Playing extras is not supported right now.
