### ISSUE TITLE
Feature Request / Bug (?) : Support multiple servers

### ISSUE THREAD

**Issue by Paul-Vdp** [JurajNyiri/PlexMeetsHomeAssistant#65]
When multiple plex servers are configured in Hass, all playing fails (at least on cast devices, not tested on other).
This is because the generated json for content_id fails to include the 'plex_server' parameter, therefore resulting in an error such as :
'Multiple Plex servers configured, choose with 'plex_server' key: ['Server1', 'Server2']'

**Comment by JurajNyiri** [comment]
What is this plex_server key referring to? Is it something that is generated by Home Assistant integration or is it something that server has, like a server ID or something similar?

**Comment by Paul-Vdp** [comment]
It is simply the 'Friendly name' as given in the Plex 'General Settings' to that server, so I am sure it is retrievable through their API, as evidenced by the fact that Hass even mentions them literally in their error message (the 'Server1' and 2 in the above message are obfuscations for the real names).
Adding something like "plex_server":"Server1" in the json and manually calling the service works perfectly ...

**Comment by JurajNyiri** [comment]
Fixed in 3.4.1.

**Comment by Paul-Vdp** [comment]
Thank you for looking into this. I just updated to the new version and tested (enabling my second Plex Server integration, trying to cast to a Google Cast), but I'm sorry to say that nothing seems to have changed or improved : I still get the same error message, complaining about the missing plex_server parameter, and of course nothing is playable anymore ...

**Comment by JurajNyiri** [comment]
@Paul-Vdp make sure to delete cache and do hard reload of your browser. You can also try a different browser. It is 100% sent now.

**Comment by Paul-Vdp** [comment]
So sorry ... I should have thought of that (I usually do, but not this time).
Thanks a lot for fixing this - it works splendidly !
