### ISSUE TITLE
Feature Request : VLC support

### ISSUE THREAD

**Issue by Paul-Vdp** [JurajNyiri/PlexMeetsHomeAssistant#66]
I would love to have the VLC Media Player included as a supported player (as it is by far the easiest one to enable local playback) ...

**Comment by JurajNyiri** [comment]
How do you launch media remotely on vlc player?

**Comment by Paul-Vdp** [comment]
I have the VLC addon installed in Hass, which makes available a media player with the 'VLC media player Telnet' integration. According to the docs, this player 'can play files on the local network, Internet or files and playlist locally saved to the /share and /media folder'. I would love to be able to use your wonderful card to activate the VLC player to play my Plex music through the local audio output of the Hass machine.

**Comment by JurajNyiri** [comment]
That sounds possible! I will take a look once i have some time.

**Comment by Paul-Vdp** [comment]
Great, really looking forward to it ! Thanks beforehand ...

**Comment by JurajNyiri** [comment]
Currently supports only **track**. Reasoning and possible future solution is described in https://github.com/JurajNyiri/PlexMeetsHomeAssistant/pull/67 . 

> I have came to the conclusion that there is no way to pass multiple links into https://www.home-assistant.io/integrations/vlc_telnet/ .
> 
> What we would need is a service in Home Assistant which allows us to generate playlist accessible via HTTP. We would then pass URL to this playlist into the `media_content_id`.
> 
> Until then, it is possible to only use `track` with `vlcTelnet` player.
