### ISSUE TITLE
Bug : Scrolling not working (Desktop + Mobile)

### ISSUE THREAD

**Issue by Mathieutremblay1** [JurajNyiri/PlexMeetsHomeAssistant#69]
When selecting a TV show for example, I cannot scroll down, it goes back up right away. On desktop, I can manually drag the scroll bar down. I am then able to scroll up only but not down using the mouse wheel. On mobile, since the scroll bar is not draggable, I can't browse titles.

Thank you!

**Checks**
Please check below if true:

[ X] I am running Home Assistant on HTTP protocol
[ ] I am running BOTH Home Assistant AND Plex on HTTPS protocol
[X ] My Plex server is accessible through protocol, port and ip/hostname I have specified for the card.
[X ] My Plex server is running on HTTPS and has a valid certificate.

type: custom:plex-meets-homeassistant
protocol: http
sort: titleSort:asc
displayType: '2'
playTrailer: false
showExtras: true
showSearch: true
ip: 10.0.XXXXX
token: XXXXXXXXXX
port: '32400'
entity:
  - plexPlayer | TV 2018 | XXXXXXXX
libraryName: TV Shows
maxCount: ''
maxRows: ''
useHorizontalScroll: 'No'
useShuffle: 'No'
displayTitleMain: 'Yes'
displaySubtitleMain: 'Yes'
minWidth: ''
minEpisodeWidth: ''
minExpandedWidth: ''
fontSize1: ''
fontSize2: ''
fontSize3: ''
fontSize4: ''
minExpandedHeight: ''
title: TV Shows

**Card Version**
3.4.1

**Plex Version**
1.25.2.5319

**Comment by JurajNyiri** [comment]
Scrolling does work for me. 
- Are you using this card in any other card or dashboard? Try it in a new panel in normal lovelace, it will work. 
- Please provide more information about your browser, device and environment

**Comment by Mathieutremblay1** [comment]
Very sorry, that was my fault. I had not activated panel mode. Thank you for the quick reply, have a great day!
