### ISSUE TITLE
Have Samsung TV and Plex on it, but the play button nowhere.

### ISSUE THREAD

**Issue by spider7611** [JurajNyiri/PlexMeetsHomeAssistant#7]
Hi,

I have Samsung TV and plex on it. My problem is not have play button. 
I know my tv ip address but nothing. On my mobile plex cast I don't see the tv only my google mini, don't know why.
On the tv I can use plex perfectly.

What is the problem?

Thank You!

**Comment by JurajNyiri** [comment]
Hello,

Follow **Machine ID setup** in https://github.com/JurajNyiri/PlexMeetsHomeAssistant#all-other-plex-clients .

**Comment by spider7611** [comment]
Ok, now see the play button everywhere but nothing happend when I click it.

**Comment by JurajNyiri** [comment]
Do you have plex app on TV turned on when you click play?

**Comment by spider7611** [comment]
Yes it was turned on.
Correct device because only see that device on the web link.

**Comment by JurajNyiri** [comment]
Did you use machineIdentifier? Or name? For my Samsung 2020 "TV 2020" worked, so maybe TV 2019 will work for you.

**Comment by spider7611** [comment]
Yes I used machineIdentifier. Will try TV 2019.

**Comment by JurajNyiri** [comment]
Good news @spider7611  there is now a workaround for some users experiencing this. Make sure to update to 1.3.1, clear cache and read https://github.com/JurajNyiri/PlexMeetsHomeAssistant#faq .

**Comment by JurajNyiri** [comment]
Should now be fixed properly without needing to do the workaround in 1.3.2.
