### ISSUE TITLE
[Feature ?] A way to add Apple TV plex app to list of entities available.

### ISSUE THREAD

**Issue by Moustik2002** [JurajNyiri/PlexMeetsHomeAssistant#70]
Hi,

I really like your work. But to match the way i would like to use your custom card, is it a way to select my apple TV entity as the player for the media i choose ?

**Comment by JurajNyiri** [comment]
Hello!

You can use UI editor to automatically detect all available target devices. Before you open it, make sure to turn on and sign in to your plex application on your apple TV. I do not know apple TV so I do not know if it works, but there were users using this integration with apple TV.

**Comment by Moustik2002** [comment]
i tried but doesn't pop up on entity available :

![image](https://user-images.githubusercontent.com/7987482/148548732-d37511c4-6657-4803-ac7f-17df36620b0e.png)


I've it up and running plex client though :

![image](https://user-images.githubusercontent.com/7987482/148548874-036ef8a5-d79d-49ce-bdc8-380ecf9eb868.png)

**Comment by JurajNyiri** [comment]
What integration created that media_player device?

**Comment by Moustik2002** [comment]
That's what i've done :) (launch Plex app on apple tv and then edit card in lovelace)

Integration used for Apple TV is this : [Apple TV beta via HACS](https://github.com/postlund/hass-atv-beta)

**Comment by JurajNyiri** [comment]
Ah that explains it. That custom integration is not supported. It also allows playing only music so wouldn't help much.
I still do not know why it wouldn't show up as a plexPlayer though. 
I recommend you asking in [Discord](https://discord.gg/jqqz9jQXWx) or [Home Assistant Community](https://community.home-assistant.io/t/custom-component-card-plex-meets-home-assistant/304349). There are users using this with apple TV afaik but I do not unfortunately own it so cannot help you further.

**Comment by mayorgergich** [comment]
Sorry to re-open this thread, but have their been any updated instructions on getting this to work with AppleTV?

**Comment by cismarine** [comment]
It works. You need to start plex app first, than search for entities. Works every time.Sent from my iPhoneOn 10. May 2024, at 19:00, mayorgergich ***@***.***> wrote:﻿
Sorry to re-open this thread, but have their been any updated instructions on getting this to work with AppleTV?

**Comment by mayorgergich** [comment]
That's interesting. I'm unable to see any devices when configuring the card that aren't my sonos integration already in home assistant. The device (browser) is currently playing from my plex server. I must be missing a step.
