### ISSUE TITLE
Android Tablet, or Android Phone no Server Connection -- Home Assistant App

### ISSUE THREAD

**Issue by pimp1310** [JurajNyiri/PlexMeetsHomeAssistant#78]
**Describe the bug**
If you try to display films via the Home Assistant App using an Android tablet or an Android phone, they remain empty, it only says "Error: PLex server did not respond -- Details of the error: Network error"

With my iPhone or the Chrome browser on my Windows Laptop it works without any problems.

**Screenshots**
![IMG_0351 (1)](https://user-images.githubusercontent.com/6306057/153939836-26271d3c-4c0f-4b12-9336-5da6085046e8.jpg)

**Checks**
Please check below if true:

[x] I am running Home Assistant on HTTP protocol
[ ] I am running BOTH Home Assistant AND Plex on HTTPS protocol
[x] My Plex server is accessible through protocol, port and ip/hostname I have specified for the card.
[ ] My Plex server is running on HTTPS and has a valid certificate.

**Card Configuration**
`type: custom:plex-meets-homeassistant
protocol: http
sort: ''
displayType: ''
playTrailer: true
showExtras: true
showSearch: true
ip: 192.168.0.53
token: 
port: '32400'
entity:
  - kodi | media_player.android
libraryName: Continue Watching
maxCount: '40'
maxRows: '3'
useHorizontalScroll: 'No'
useShuffle: 'No'
displayTitleMain: 'Yes'
displaySubtitleMain: 'Yes'
minWidth: ''
minEpisodeWidth: ''
minExpandedWidth: ''
fontSize1: ''
fontSize2: ''
fontSize3: ''
fontSize4: ''
minExpandedHeight: ''
title: Weiterschauen`

**Card Version**
3.6.1

**Plex Version**
Version 4.69.1

**Device information**
Amazon Fire HD 10 Tablet 
Galaxy s21 (Android 12)

**Additional context**
as I said before, strangely enough, it works on my iPhone and the browser without any problems. I don't know exactly why it doesn't work on Android devices.

If I can help then just let me know, I'm happy to do so

**Comment by JurajNyiri** [comment]
User was using HTTPS Home Assistant with HTTP plex. Debugged on discord, closing.
