### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Markker98** [JurajNyiri/PlexMeetsHomeAssistant#79]
---
name: Bug report
about: Create a report to help us improve
title: Bug
labels: ''
assignees: 

---

**Describe the bug**

**To Reproduce**
1. Go to 'Play any media file'

**Expected behavior**
Some media is not having audio playback. Media status (for example played) not updated if started from card.

**Screenshots**
If this is a network error, please open network tab in your browser developer tools and paste in as much information as possible about the failing request. This will make it a lot easier to help you as soon as possible.

**Checks**
Please check below if true:

[ Yes] I am running Home Assistant on HTTP protocol
[ NO both HTTP] I am running BOTH Home Assistant AND Plex on HTTPS protocol
[Yes ] My Plex server is accessible through protocol, port and ip/hostname I have specified for the card.
[No ] My Plex server is running on HTTPS and has a valid certificate.

**Card Configuration**
type: custom:plex-meets-homeassistant
protocol: http
sort: ''
displayType: ''
playTrailer: false
showExtras: false
showSearch: false
ip: 
token: 
port: '32400'
entity:
  - cast | media_player.tv
libraryName: Continue Watching
maxCount: ''
maxRows: '2'
useHorizontalScroll: 'No'
useShuffle: 'No'
displayTitleMain: 'No'
displaySubtitleMain: 'No'
minWidth: ''
minEpisodeWidth: ''
minExpandedWidth: ''
fontSize1: ''
fontSize2: ''
fontSize3: ''
fontSize4: ''
minExpandedHeight: ''
title: Fortsetzen

**Card Version**
3.6.1

**Plex Version**
1.25.5.5492 

**Device information**
Chrome

**Additional context**
The playbackd evice is a chromecast

**Comment by JurajNyiri** [comment]
Status will not be updated when played through cast. If your media doesn't have audio, your target device doesn't support your file codecs.

**Comment by Markker98** [comment]
The audio playback works fine from the cast function in plex. Some files have multiple aufio tracks. Plex usally selects the most appropriate. Using the card sometimes the wrong audio gets selected ( for example with comentary or different language)

**Comment by JurajNyiri** [comment]
Make sure to use [plex](https://www.home-assistant.io/integrations/plex/) integration when using cast via card for the best experience.
