### ISSUE TITLE
Bug: Chrome/Chromium issues on Android devices and Raspberry Pi's running Chromium

### ISSUE THREAD

**Issue by Thursty24** [JurajNyiri/PlexMeetsHomeAssistant#87]
The PMHA integration works great, however, it seems that when using it on an android phone with Chrome/Chromium or Raspberry Pi running Chrome, the play button on the content is grayed out, however if using this on a windows PC with Chrome, there are no issues with the Play button.

**Comment by JurajNyiri** [comment]
Duplicate of https://github.com/JurajNyiri/PlexMeetsHomeAssistant/issues/60 . Please focus discussion in there.
