### ISSUE TITLE
Feature Request: Cast to all

### ISSUE THREAD

**Issue by c11umw** [JurajNyiri/PlexMeetsHomeAssistant#89]
Hi
I saw the video of the card and saw the 3rd option of "All Clients"

In the detailed card setup I could only see an option for the system playing on the first device that wasn't unavailable.

Is there a way to have this cast to all available devices?
It would make whole home music a great thing

**Comment by JurajNyiri** [comment]
This would not work well as music would not be synchronized. If you are using google home, look into grouping your speakers into one group. That will be presented as a single entity in HA.
