### ISSUE TITLE
Feature request: add support for Google Chromecast streaming

### ISSUE THREAD

**Issue by andrey-yantsen** [JurajNyiri/PlexMeetsHomeAssistant#9]
First of all, thank you for the great idea, the card looks lovely!

Can you please add support for casting the media to Google Chromecast?

**Comment by JurajNyiri** [comment]
Does chromecast show up in https://github.com/JurajNyiri/PlexMeetsHomeAssistant#all-other-plex-clients machine ID setup? If yes, you can add it that way. If not, this will need to be supported later on.

**Comment by andrey-yantsen** [comment]
Nope — it's not a real client, and even registered in the Plex API.

**Comment by JurajNyiri** [comment]
Ah I see, I will implement this some time in the future but its not the highest priority right now. PRs are welcomed.

**Comment by JurajNyiri** [comment]
@andrey-yantsen Google Cast is now supported. https://github.com/JurajNyiri/PlexMeetsHomeAssistant#google-cast

**Comment by andrey-yantsen** [comment]
That was fast, thank you!
