### ISSUE TITLE
Multi user support?

### ISSUE THREAD

**Issue by addrum** [JurajNyiri/PlexMeetsHomeAssistant#92]
Apologies if I've missed this in the readme or other issues. Currently when I open the Plex app on my TV I have it set to not auto login as I have a few managed users setup (a bit like Netflix). Launching a film or program from this card appears to not work unless one of the accounts is chosen already; does the card support choosing a managed user?

**Comment by JurajNyiri** [comment]
Unfortunately this is not possible. It uses whatever token is set to communicate with plex.
