### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Jefftrmb** [JurajNyiri/PlexMeetsHomeAssistant#93]
**Describe the bug**
Roku Plex Player Returns Error: Failed to Call Service rest_command pmha_playmedia. Service not found.

No commands are received or executed by Roku Plex Player. 

**Screenshots**
If this is a network error, please open network tab in your browser developer tools and paste in as much information as possible about the failing request. This will make it a lot easier to help you as soon as possible.

**Checks**
Please check below if true:

[ x] I am running Home Assistant on HTTP protocol
[ ] I am running BOTH Home Assistant AND Plex on HTTPS protocol
[ x] My Plex server is accessible through protocol, port and ip/hostname I have specified for the card.
[ ] My Plex server is running on HTTPS and has a valid certificate.

**Card Configuration**
type: custom:plex-meets-homeassistant
protocol: http
sort: titleSort:asc
playTrailer: false
showExtras: true
showSearch: true
ip: 192.**************
token: Wg******************
port: '32400'
entity:
  - >-
    plexPlayer | 75" Hisense Roku TV | 192.******** |
    5b62e75**********************
libraryName: Movies
maxCount: ''
maxRows: ''
useHorizontalScroll: 'No'
useShuffle: 'No'
displayTitleMain: 'Yes'
displaySubtitleMain: 'Yes'
minWidth: ''
minEpisodeWidth: ''
minExpandedWidth: ''
fontSize1: ''
fontSize2: ''
fontSize3: ''
fontSize4: ''
minExpandedHeight: ''
title: ''
runBefore: ''
runAfter: ''

**Card Version**
3.6.5

**Plex Version**
Roku Plex Player 7.0.30

**Device information**
Android and IOS HA App
Chrome

**Comment by JurajNyiri** [comment]
Duplicate https://github.com/JurajNyiri/PlexMeetsHomeAssistant/issues/82 .
