### ISSUE TITLE
No Longer Able to Scroll Vertically

### ISSUE THREAD

**Issue by frankietest6** [JurajNyiri/PlexMeetsHomeAssistant#95]
I've tried scrolling in my card using a chrome browser on Windows and in the Android Home Assistant App. There just doesn't seem to be any scroll bar for some reason. I'm just stuck with the first movies that show up in order until it's out of space. I'll post my other info below.

type: custom:plex-meets-homeassistant
protocol: http
sort: titleSort:asc
playTrailer: true
showExtras: true
showSearch: true
ip: ***.***.***.***
token: 
port: '32400'
libraryName: Main Movies
entity:
  - androidtv | media_player.braviatv
maxCount: ''
maxRows: ''
useHorizontalScroll: 'No'
useShuffle: 'No'
displayTitleMain: 'Yes'
displaySubtitleMain: 'Yes'
minWidth: ''
minEpisodeWidth: ''
minExpandedWidth: ''
fontSize1: ''
fontSize2: ''
fontSize3: ''
fontSize4: ''
minExpandedHeight: ''
title: Movies
runBefore: ''
runAfter: ''

Plex Verson: 1.32.0.6973
Card Version: 3.6.7

**Comment by JurajNyiri** [comment]
What HA version? It works for me in latest ha as per today.

**Comment by JurajNyiri** [comment]
Could you post some screenshots?

**Comment by frankietest6** [comment]
![Screenshot_20230426_182409_Home Assistant](https://user-images.githubusercontent.com/81137178/234723529-d9ad17ad-e346-4772-b2ca-1f75a63aa018.jpg)

**Comment by frankietest6** [comment]
![Screenshot_20230426_182719_Home Assistant](https://user-images.githubusercontent.com/81137178/234723642-6818cf78-74e8-4126-a1c9-a6d57d10ff07.jpg)

**Comment by frankietest6** [comment]
I don't understand what might be causing this.

**Comment by JurajNyiri** [comment]
Are you using any theme that could be preventing the use of scrollbar?

**Comment by frankietest6** [comment]
I don't believe so. My regular dashboard page has scroll bars just fine.

**Comment by frankietest6** [comment]
I'll do some testing with it here in just a little bit when I get home.

**Comment by frankietest6** [comment]
So I disabled all themes platform wide, and I still can't scroll.

**Comment by frankietest6** [comment]
I just figured it out. In had my pages set as Panel(1 card) and apparently
that causes this issue. I changed it to "sidebar" to fill the page and it
works flawlessly now. Sorry for the confusion, and I appreciate the help.
